services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    command: --config /etc/livekit.yaml
    volumes:
      - ./configs/livekit/livekit.yaml:/etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50100:50000-50100/udp"

  web:
    build:
      context: ../..
      dockerfile: infra/docker/services/web/Dockerfile
    image: meet-frontend:latest
    container_name: web
    environment:
      LIVEKIT_URL: "ws://localhost:7880"
      LIVEKIT_API_KEY: devkey
      LIVEKIT_API_SECRET: secret
    depends_on:
      - livekit

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
